name: "Build and push pnpm image"
on:
  push:
    branches:
      - 'main'
jobs:
  build-test-push-images:
    strategy:
      fail-fast: false
      matrix:
        tag: ["22", "22-alpine"]
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t pnpm-image:latest ./images/${{ matrix.tag }}
      - name: Building Sample Application
        run: |
          docker build -f ./sample-app/Dockerfile ./sample-app/next-app
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker Image
        run: |
          if [ ${{ matrix.runner }} == "ubuntu-24.04" ]; then
            export ARCH=amd64;
          elif [ ${{ matrix.runner }} == "ubuntu-24.04-arm" ]; then
            export ARCH=arm64;
          else
            echo "Unknown runner";
            exit 1;
          fi
          docker tag pnpm-image:latest ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}-$ARCH
          docker push ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}-$ARCH
          echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}-$ARCH)"
  create-manifest:
    needs: build-test-push-images
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        tag: ["22", "22-alpine"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Create manifest
        run:    |
          docker manifest create ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }} \
            ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}-amd64 \
            ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}-arm64
          docker manifest push ${{ vars.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.tag }}
