name: "Build and push pnpm image"
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - './.github/workflows/build-and-push.yaml'
jobs:
  find-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-changes.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed directories
        id: get-changes
        run: |
          BEFORE_COMMIT=${{ github.event.before }}
          CURRENT_COMMIT=${{ github.sha }}
          # Get the list of changed directories under the images folder
          CHANGED_DIRS=$(git diff --name-only $BEFORE_COMMIT $CURRENT_COMMIT | grep '^images/' | cut -d/ -f2 | sort | uniq)
          echo "Changed directories: $CHANGED_DIRS"
          # if there are no changes, set an empty array
          if [ -z "$CHANGED_DIRS" ]; then
            TAGS="[]"
          else
            # Convert the list to JSON array format
            EXISTING_DIRS=$(find images -type d -mindepth 1 -maxdepth 1 | cut -d/ -f2 | sort | uniq)
            FILTERED_DIRS=$(comm -12 <(echo "$CHANGED_DIRS") <(echo "$EXISTING_DIRS"))
            TAGS=$(printf '%s\n' "$FILTERED_DIRS" | jq -R . | jq -sc .)
          fi
          echo "tags=$TAGS"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
  build-images:
    needs: find-changed-dirs
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.find-changed-dirs.outputs.tags) }}
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: pnpm-image:${{ matrix.tag }}
          context: ./images/${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
      - name: Building Sample Application
        run: |
          docker build -f ./sample-app/Dockerfile ./sample-app/next-app
